// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"activity-api/internal/biz"
	"activity-api/internal/conf"
	"activity-api/internal/data"
	"activity-api/internal/server"
	"activity-api/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	solidActivityRepo := data.NewSolidRepo(dataData, logger)
	solidActivityUsecase := biz.NewSolidActivityUsecase(solidActivityRepo, logger)
	solidService := service.NewSolidService(solidActivityUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, solidService, logger)
	httpServer := server.NewHTTPServer(confServer, solidService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
